version: '3.8'

volumes:
  mongo_volume:

networks:
  rotten-network:
    driver: bridge

services: 
  mongo:
    image: mongo:4.4.3
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    volumes:
      - mongo_volume:/data/db
    networks:
      - rotten-network
      
  rotten:
    image: jhtoigo/rotten-potatoes:${TAG}
    build:
      dockerfile: Dockerfile
      context: ./src
    ports:
      - ${WEBPORT}:${PORT}
    networks:
      - rotten-network
    environment:
      MONGODB_DB: ${MONGODB_DB}
      MONGODB_HOST: ${MONGODB_HOST}
      MONGODB_PORT: ${MONGODB_PORT}
      MONGODB_USERNAME: ${MONGODB_USERNAME}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
    depends_on:
      - mongo

